### ISSUE TITLE
Possible error in Exercise 1

### ISSUE THREAD

**Issue by timmyjose** [erhant/moonmath#18]
Exercise: https://github.com/erhant/moonmath/blob/master/arithmetics/README.md#exercise-5

We have to find the Euclidean decomposition of (-1687, 11). The given solution is (-153, 7), but that doesn't solve the equation:

```
  -1687 = (-153) x 11 + 7
```

whereas (-154, 7) does solve the equation:

```
  -1687 = (-154) * 11 + 7
```

**Comment by erhant** [comment]
Hi! I had an issue for this (https://github.com/erhant/moonmath/issues/14) but had closed it because the current only open PR has the fix, I will reopen the older one and close this one.

Thanks for your attention 🙏🏻
