### ISSUE TITLE
Exc. 82

### ISSUE THREAD

**Issue by erhant** [erhant/moonmath#19]
$\mathbb{G}_1$ and $\mathbb{G}_2$ turn out to be equal because $k=1$ in this case? Is our solution correct?

**Comment by erhant** [comment]
Also, full 2-torsion group is expected to contain 2^2=4 elements, but we only see 2 elements?

**Comment by erhant** [comment]
Suggestion by @skaunov was to use a torsion group of a curve from extended field, since beyond the powers of embedding degree, the torsion groups are equal. However, I still want to find the correct group using the embedding degree itself, without going beyond it.

His original solution used k=4 and it does return 4 elements:

> ```py
> F13 = GF(13)
> TJJ_F13 = EllipticCurve(F13, [8, 8])
> for point in TJJ_F13.points():
>     if point.order() == 2:
>         print(point)
> 
> L_TJJ_T2 = []
> for i in range(1, 3):
>     L_TJJ_T2.append(i * TJJ_F13([4, 0]))
> TJJ_T2 = Set(L_TJJ_T2)
> print(TJJ_T2)
> # {(4 : 0 : 1), (0 : 1 : 0)}
> F13t.<t> = F13[]
> P_MOD_4 = F13t(t^4 + 2) # see previous exercises with this curve
> F13_4.<t> = GF(13^4, name='t', modulus=P_MOD_4)
> 
> TJJ_F13_4 = EllipticCurve(F13_4, [8, 8])
> # There's a dozen of elements of order $2^2$!
> # for point in TJJ_F13_4.points():
> #     if point.order() == 4:
> #         print(point)
> # So let's fall back to the approach from the page #103.
> TJJF13_4_2 = Set(TJJ_F13_4(0).division_points(2))
> TJJF13_4_2
> # {(4 : 0 : 1), (7*t^2 + 11 : 0 : 1), (6*t^2 + 11 : 0 : 1), (0 : 1 : 0)}
> 
> # $\mathbb{G}_{1}[2]$ equals 2-torsion group
> TJJ_G1 = Set([TJJ_F13_4(point) for point in TJJ_T2])
> TJJ_G1
> ```
> 
> Let's look more closely at TJJF13_4_2. It contains (0 : 1 : 0) and three more points. We know that there's $r +1$ r-torsion subgroups, and we have $r = 2$, so each of this three points would suit; remember that zero-degree (4, 0) gives us $\mathbb{G}_1[2]$, so $\mathbb{G}_2[2]$ is equally good to generate with either one of two other points from TJJF13_4_2. The second element will be inevitable $(0 : 1 : 0)$.

**Comment by skaunov** [comment]
Just for the sake of discussion: I found it quite hard and unproductive to think about such minimal pairing groups. Funny edge case ofc. but still. My best guess is that authors really wanted to have "book-through" examples, and TJJ yields only two possible variants better of which went into the text example, and with the other we're dealing here as an exercise, lol.

**Comment by erhant** [comment]
In the code below, we can see the difference between using the base field vs extended field.

```py
# curve parameters for TJJ_13
p = 13
a, b = 8, 8

F13 = GF(p)      # field
F13t.<t> = FP[]  # polynomial ring 
r = 2            # prime factor


def pairings(E, E_tor):
    print(E)

    # frobenius
    def fro_pi(P):
        if P != E(0):
            (x, y) = P.xy()
            return E(x^p, y^p)
        else:
            return P

    G1 = [P for P in E_tor if fro_pi(P) == P]
    print("G1:", G1)
    # {(4 : 0 : 1), (0 : 1 : 0)}

    G2 = [P for P in E_tor if fro_pi(P) == p*P]
    print("G2:", G1)

# curve over the base field
TJJ = EllipticCurve(F13, [a, b])
assert TJJ.order() % r == 0

# r-torsion group over base curve
TJJ_tor = TJJ(0).division_points(r)
print("2-torsion over p^1 (full)\n\t", TJJ_tor)
pairings(TJJ, TJJ_tor)

# curve over extension field of 4
F13_4 = GF(p^4, name='t', modulus=F13t.irreducible_element(4))
TJJ_4 = EllipticCurve(F13_4, [a, b])

# r-torsion group over extended curve
TJJ_4_tor = TJJ_4(0).division_points(r)
print("2-torsion over p^4\n\t", TJJ_4_tor)
pairings(TJJ_4, TJJ_4_tor)
```

**Comment by erhant** [comment]
copy-pasting my message to ZKHACK study group:

to find a full r-torsion group, we must find the r-torsion group of the curve over an extended field of F_{p^k(r)} where k(r) is the embedding degree for r

as also shown in an exmaple, when r=2, we immediately find k=1 for a prime base field order. so our "extended" field is actually the base field itself F_{p^1}

when I find the torsion group this way, I only find 2 elements that satisfy 2*P = INF
the book states that a full r-torsion group should have r^2 elements, so thats a problem

furthermore, when I find the 2-torsion group for F_{p^4} I actually get 4 elements for the first time, the torsion groups up to this point all have 2 elements and from this point on we have 4 elements. based on eq (5.4.4) this should indicate 4 to be the embedding degree, but that contradicts the stuff we did at the start

**Comment by erhant** [comment]
Added more comments to the solution, see PR #22
