### ISSUE TITLE
Exc. 93: Contradictory answers

### ISSUE THREAD

**Issue by kashepavadan** [erhant/moonmath#38]
https://github.com/erhant/moonmath/tree/master/elliptic-curves#exercise-93-

You write the following:

> We are given the addition table of the subgroup of order 13 (page 128), and the point (9, 2) does not appear there. This means that our point belongs to the subgroup of order 3. Therefore, [3](9, 2) results in the point at infinity.

Then, in the Sage code, you compare the answer to (13, 15):

`from sage.all import GF, EllipticCurve`

`BLS6_6 = EllipticCurve(GF(43), [0, 6])`
`assert BLS6_6(9, 2) * 3 == BLS6_6(13, 15)`

The second answer should be the correct one, and this is confirmed by the textbook itself on page 127.

**Comment by erhant** [comment]
Thank you for the issue, been really busy these days but I will try to fix 👍🏻 
Would love a PR as well!
